[workspace]
resolver = "2"
members = [
  "nixrs",
  "nixrs-sys"
]

[workspace.package]
edition = "2021"
rust-version = "1.77"
license = "MIT"
version = "0.1.0"
description = "nix bindings for Rust"
repository = "https://github.com/Anillc/nixrs"
homepage = "https://github.com/Anillc/nixrs"
