[package]
name = "nixrs-sys"

description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[build-dependencies]
bindgen = "0.69.4"
pkg-config = "0.3.30"
